#+TITLE:  Documents and presentations with org-mode
#+AUTHOR: John Goerzen
#+BEAMER_HEADER: \institute{The Changelog}
#+PROPERTY: comments yes
#+PROPERTY: header-args :exports both :eval never-export
#+OPTIONS: H:2
#+BEAMER_THEME: CambridgeUS
#+BEAMER_COLOR_THEME: default

# We can't just +BEAMER_INNER_THEME: default because that picks the theme default.
# Override per https://tex.stackexchange.com/questions/11168/change-bullet-style-formatting-in-beamer
#+BEAMER_INNER_THEME: default
#+LaTeX_CLASS_OPTIONS: [aspectratio=169]
#+BEAMER_HEADER: \definecolor{links}{HTML}{0000A0}
#+BEAMER_HEADER: \hypersetup{colorlinks=,linkcolor=,urlcolor=links}
#+BEAMER_HEADER: \setbeamertemplate{itemize items}[default]
#+BEAMER_HEADER: \setbeamertemplate{enumerate items}[default]
#+BEAMER_HEADER: \setbeamertemplate{items}[default]
#+BEAMER_HEADER: \setbeamercolor*{local structure}{fg=darkred}
#+BEAMER_HEADER: \setbeamercolor{section in toc}{fg=darkred}
#+BEAMER_HEADER: \setlength{\parskip}{\smallskipamount}
#+BEAMER_HEADER: \AtBeginSection{\frame{\sectionpage}}

** The Emacs series

This is fifth in a [[https://changelog.complete.org/archives/tag/emacs2018][series on Emacs and org-mode]].

This document was generated from [[https://github.com/jgoerzen/public-snippets/blob/master/emacs/emacs-org-beamer.org][an org-mode source]] and exported
as PDF slides and a blog page.

* About org-mode exporting
** Background

org-mode isn't just an agenda-making program.  It can also export to
lots of formats: LaTeX, PDF, Beamer, iCalendar (agendas), HTML,
Markdown, ODT, plain text, man pages, and more complicated formats
such as a set of web pages.

This isn't just some afterthought either; it's a core part of the
system and integrates very well.

One file can be source code, automatically-generated output, task
list, documentation, and presentation, all at once.

Some use org-mode as their preferred markup format, even for things
like LaTeX documents.  The org-mode manual has an extensive [[https://orgmode.org/manual/Exporting.html#Exporting][section on
exporting]].

** Getting started

From any org-mode document, just hit =C-c C-e=.  From there will come
up a menu, letting you choose various export formats and options.
These are generally single-key options so it's easy to set and
execute.  For instance, to export a document to a PDF, use 
=C-c C-e l p= or for HTML export, =C-c C-e h h=.

There are lots of settings available for all of these export options;
see the manual.  It is, in fact, quite possible to use LaTeX-format
equations in both LaTeX and HTML modes, to insert arbitrary preambles
and settings for different modes, etc.

** Add-on packages

ELPA containts many addition exporters for org-mode as well.  Check
there for details.

* Interactive Slides
** Interactive Emacs Slideshows

With the [[https://orgmode.org/worg/org-tutorials/non-beamer-presentations.html#org-tree-slide][org-tree-slide package]], you can display your slideshow from
right within Emacs.  Just run =M-x org-tree-slide-mode=.  Then, use
the left and right arrows to move between slides.

You might find =C-c C-x C-v= (which is =org-toggle-inline-images=)
helpful to cause the system to display embedded images.


* Beamer Slides with org-mode


* Miscellaneous
** Resources to accompany this post

 - [[https://orgmode.org/worg/exporters/beamer/tutorial.html][orgmode.org beamer tutorial]]
 - [[https://en.wikibooks.org/wiki/LaTeX/Presentations][LaTeX wiki]]
 - [[https://tex.stackexchange.com/questions/117658/automatically-generate-section-title-slides-in-beamer/117661][Generating section title slides]]
 - [[https://tex.stackexchange.com/questions/78514/content-doesnt-fit-in-one-slide][Shrinking content to fit on slide]]
 - A *great* resource: refcard-org-beamer
   - See its [[https://github.com/fniessen/refcard-org-beamer][Github repo]]
   - Make sure to check out both the PDF and the .org file
 - A nice [[https://hartwork.org/beamer-theme-matrix/][Theme matrix]]


